### ISSUE TITLE
Tracking error is too high but the feature is not lost 

### ISSUE THREAD

**Issue by UtharaKeerthan** [LarryDong/FusionTracking#1]
Hi, 
Thanks for this repository. I'm using this repository to run the ICP algorithm and the Data fusion algorithm on the [DSEC](https://dsec.ifi.uzh.ch/) dataset. 

While running both the icp and the fusion algorithm, it was observed that the tracking error is too high for the registered features but still the tracking is happening. Due to this, the feature age of a tracking in icp is greater than the feature age of the actual ground truth tracking that is done only using the frames and by doing KLT.  Please find the following lines of logs about the feature id, feature age from icp and grund truth for running the evaluation code from [Tracking analysis package](https://github.com/uzh-rpg/rpg_feature_tracking_analysis) with an error threshold of 0.

('Feature ID:', 0.0, 'Feature age from ICP:', 6.61019299999316, 'Feature age from KLT(ground truth):', 1.4999909999969532)
('Feature ID:', 2.0, 'Feature age from ICP:', 12.125508999997692, 'Feature age from KLT(ground truth):', 1.2999940000008792)
('Feature ID:', 3.0, 'Feature age from ICP:', 2.738868000000366, 'Feature age from KLT(ground truth):', 5.950016000002506)
('Feature ID:', 4.0, 'Feature age from ICP:', 11.08009299999685, 'Feature age from KLT(ground truth):', 1.3499910000027744)
('Feature ID:', 5.0, 'Feature age from ICP:', 12.061234999993758, 'Feature age from KLT(ground truth):', 2.8500219999987166)
('Feature ID:', 6.0, 'Feature age from ICP:', 11.883297000000312, 'Feature age from KLT(ground truth):', 5.950016000002506)
('Feature ID:', 7.0, 'Feature age from ICP:', 12.255395000000135, 'Feature age from KLT(ground truth):', 1.4500009999974282)
('Feature ID:', 8.0, 'Feature age from ICP:', 12.185082999996666, 'Feature age from KLT(ground truth):', 5.300036000000546)
('Feature ID:', 9.0, 'Feature age from ICP:', 12.37140399999771, 'Feature age from KLT(ground truth):', 9.10044100000232)
('Feature ID:', 10.0, 'Feature age from ICP:', 12.36969699999463, 'Feature age from KLT(ground truth):', 7.949991000001319)
('Feature ID:', 11.0, 'Feature age from ICP:', 11.381970999995247, 'Feature age from KLT(ground truth):', 5.450042999997095)
('Feature ID:', 13.0, 'Feature age from ICP:', 12.356047999994189, 'Feature age from KLT(ground truth):', 6.450007999999797)
('Feature ID:', 14.0, 'Feature age from ICP:', 2.852735999993456, 'Feature age from KLT(ground truth):', 6.749961000001348)
('Feature ID:', 15.0, 'Feature age from ICP:', 12.373615999997128, 'Feature age from KLT(ground truth):', 2.699975000003178)
('Feature ID:', 16.0, 'Feature age from ICP:', 12.237728000000061, 'Feature age from KLT(ground truth):', 2.200011000000813)
('Feature ID:', 18.0, 'Feature age from ICP:', 1.507607999999891, 'Feature age from KLT(ground truth):', 0.14998400000331458)
('Feature ID:', 19.0, 'Feature age from ICP:', 6.754004999995232, 'Feature age from KLT(ground truth):', 2.699975000003178)
('Feature ID:', 20.0, 'Feature age from ICP:', 12.140934999995807, 'Feature age from KLT(ground truth):', 2.800008999998681)
('Feature ID:', 21.0, 'Feature age from ICP:', 3.3948749999981374, 'Feature age from KLT(ground truth):', 0.34997399999701884)
('Feature ID:', 23.0, 'Feature age from ICP:', 4.019961999998486, 'Feature age from KLT(ground truth):', 13.350574999996752)
('Feature ID:', 24.0, 'Feature age from ICP:', 11.931282999998075, 'Feature age from KLT(ground truth):', 9.400547999997798)
('Feature ID:', 25.0, 'Feature age from ICP:', 11.533753999996406, 'Feature age from KLT(ground truth):', 13.350574999996752)
('Feature ID:', 26.0, 'Feature age from ICP:', 10.897391999998945, 'Feature age from KLT(ground truth):', 9.30052599999908)
('Feature ID:', 27.0, 'Feature age from ICP:', 1.4430959999954212, 'Feature age from KLT(ground truth):', 0.34997399999701884)
('Feature ID:', 28.0, 'Feature age from ICP:', 4.775770000000193, 'Feature age from KLT(ground truth):', 1.2999940000008792)
('Feature ID:', 29.0, 'Feature age from ICP:', 7.4957849999991595, 'Feature age from KLT(ground truth):', 5.400026000002981)
('Feature ID:', 30.0, 'Feature age from ICP:', 3.2809719999931986, 'Feature age from KLT(ground truth):', 3.0500269999974985)
('Feature ID:', 31.0, 'Feature age from ICP:', 8.937173999998777, 'Feature age from KLT(ground truth):', 0.5999880000017583)
('Feature ID:', 32.0, 'Feature age from ICP:', 12.123510999997961, 'Feature age from KLT(ground truth):', 3.2000350000016624)
('Feature ID:', 33.0, 'Feature age from ICP:', 8.123750999999174, 'Feature age from KLT(ground truth):', 1.0499800000034156)
('Feature ID:', 34.0, 'Feature age from ICP:', 12.37807199999952, 'Feature age from KLT(ground truth):', 1.25)
('Feature ID:', 35.0, 'Feature age from ICP:', 11.678640999998606, 'Feature age from KLT(ground truth):', 6.749961000001348)
('Feature ID:', 36.0, 'Feature age from ICP:', 1.402074999998149, 'Feature age from KLT(ground truth):', 0.1999740000028396)
('Feature ID:', 39.0, 'Feature age from ICP:', 12.36537299999327, 'Feature age from KLT(ground truth):', 1.7999750000017232)
('Feature ID:', 40.0, 'Feature age from ICP:', 12.367930000000342, 'Feature age from KLT(ground truth):', 4.850032000002102)
('Feature ID:', 41.0, 'Feature age from ICP:', 6.2571959999986575, 'Feature age from KLT(ground truth):', 0.6999230000001262)
('Feature ID:', 42.0, 'Feature age from ICP:', 12.333395999994536, 'Feature age from KLT(ground truth):', 2.600032000002102)
('Feature ID:', 43.0, 'Feature age from ICP:', 10.8643449999945, 'Feature age from KLT(ground truth):', 1.4000079999968875)
('Feature ID:', 44.0, 'Feature age from ICP:', 8.922489999997197, 'Feature age from KLT(ground truth):', 0.5999880000017583)

I'm computing the normalized feature age for all the features, so I'm setting the error threshold as 0 instead a positive value like 5 or 10. Normalized feature age = feature age from icp/feature age from ground truth KLT. So that we get to know how well a feature has been tracked compared to its ground truth tracks. In the case of icp, since the feature age from icp is greater than the feature age from the ground truth, the normalized values exceed 1. 

I would like to know if the parameters in the icp.config file should be updated accordingly to reduce the error ? Could you please provide a suggestion to update the config parameters ? I have attached the following lines from the **icp.config**, that I used,

```
# feature extraction
--min_corners=0
--corner_number=45
--min_distance=30
--quality_level=0.01
--block_size=9
--k=0.04
--canny_th1=90
--canny_th2=120

# icp parameters. More strict.
--icp_events_ratio=1
--icp_error_inliers=0.7
--icp_error_mse=1.5
--icp_inlier_change=0.01
--icp_mse_change=0.05
--icp_inlier_pixel=2.5

# feature update parameters. Useless for icp method.
--image_update_velocity_th=20
--image_update_omega_th=20
--add_new_features=0
--update_features=0
--show_image=1
```

I have changed the feature extraction parameters of min_distance and block_size as 3 times the original value given by you. Since the DSEC dataset sensor size is almost 3 times bigger than the Event camera Dataset. 

The following lines are for the **uft.config** file that I'm using,
```
# feature extraction
--min_corners=0
--corner_number=45
--min_distance=30
--quality_level=0.01
--block_size=9
--k=0.04
--canny_th1=90
--canny_th2=100

# icp parameterse
--icp_events_ratio=0.5
--icp_error_inliers=0.7
--icp_error_mse=1.5
--icp_inlier_change=0.01
--icp_mse_change=0.05
--icp_inlier_pixel=2.5

# feature update parameters
--image_update_velocity_th=20
--image_update_omega_th=20

# running control
--add_new_features=0
--update_features=1
--show_image=0
```

Kindly provide your feedback on this if the **icp and the feature update parameters** that I'm using are okay for the DSEC dataset for feature tracking using icp and fusion tracker. Also, it would be a great help if a description of all the parameters on the config file is provided.  Thanks a lot.

**Comment by LarryDong** [comment]
Hi,

First, some comments:

1. Both the ICP & Fusion methods assume a feature is lost when the registration step cannot converge, and the fusion method would check if the ECC is satisfied if you enabled it. See [this](https://github.com/LarryDong/FusionTracking/blob/eeddc59ce8c21c057e57d78ed3d96f1a4b7fba34/fusion_tracker/src/fusion_tracker.cpp#L341)
2. I am not sure if the ground truth of RPG's tracking analysis package (using tranditional KLT) is accurate. 
3. For ICP method, the feature may drift in a long term so the fusion method try to limit the drift on every frame. 

Now back to your questions,
- >the tracking error is too high for the registered features but still the tracking is happening.   

In tracking phase, feature is "alive" if the ICP or Fusion method doesn't fail. The error, to be exact, is the "distance" between RPG's tool and feature position by this code.

- > Normalized feature age = feature age from icp/feature age from ground truth KLT. So that we get to know how well a feature has been tracked compared to its ground truth tracks. 

The feature age from this code could be longer than KLT's. As I explained above, the RPG's tool is also based on pure image. Maybe you could using other methods to provide **REAL** ground truth, like project a stable feature point in 3D sapce into image based on the camera view. But I guess it is hard to implement.

- > I have changed the feature extraction parameters of min_distance and block_size as 3 times the original value given by you. 

Changing the `min_distance` is reasonable. But your `block_size` is 9, which I think is much smaller. I used 25 as the spatial window size, and I think it should not be too large even the image resolution is much larger. Other configures seem good I think.

I'm not sure I have understood your questions and explained well. Feel free to reply.

**Comment by UtharaKeerthan** [comment]
Hi, Thanks for replying to all the queries that I had.
